spring.application.name=rate-limiting-service
server.port=8080
spring.cloud.gateway.discovery.locator.enabled=true

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000

rate-limiter.capacity=10
rate-limiter.refill-rate=5
rate-limiter.api-server-url=http://localhost:8080
rate-limiter.timeout=5000